Cloud 2798
jboss-container-images/jboss-eap-7-openshift-image pull request #133
Opened 2018-08-22 18:51 UTC by luck3y

https://issues.jboss.org/browse/CLOUD-2798
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2018-08-23 01:42 UTC, bstansberry requested changes

2018-08-23 01:42 UTC, bstansberry commented on image.yaml
> +from: "jboss-eap-7/eap-cd:14.0"
I'll change https://github.com/jboss-container-images/jboss-eap-7-image/pull/93 so image.yaml there says 14.0.

2018-08-23 01:42 UTC, bstansberry commented on templates/eap-cd-amq-s2i.json
> +        "xpaas": "14.0"
IIRC the 'version' field in 'metadata' : 'annotations' above is supposed to match this. 

This same comment applies to all the templates.

2018-08-23 02:39 UTC, bstansberry commented on image.yaml
> +from: "jboss-eap-7/eap-cd:14.0"
Done

2018-08-24 03:33 UTC, luck3y commented
@bstansberry I think this should be g2g now.

2018-08-24 17:52 UTC, bstansberry approved these changes

2018-08-28 13:05 UTC, merged