CLOUD-3128 - EAP 7.2 UBI OpenShift image
jboss-container-images/jboss-eap-7-openshift-image pull request #234
Opened 2019-05-02 23:40 UTC by luck3y

https://issues.jboss.org/browse/CLOUD-3128
Signed-off-by: Ken Wills <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2019-05-03 15:55 UTC, rgdoliveira submitted a review, later dismissed

2019-05-07 22:44 UTC, bstansberry requested changes
Can this be squashed when ready?

2019-05-07 22:44 UTC, bstansberry commented on cp-overrides.yaml
> +        ref: master
sprint-35?

Not master.

2019-05-07 22:44 UTC, bstansberry commented on rel-overrides.yaml
> +        ref: master
sprint-35?

Not master.

2019-05-07 22:46 UTC, luck3y commented
Yes to squash and will fix sprints.

2019-05-07 23:01 UTC, luck3y commented
@bstansberry Fixed and squashed.

2019-05-10 02:03 UTC, bstansberry approved these changes

2019-05-10 02:06 UTC, merged