CLOUD-4080 - EAP XP 4.0 Images
jboss-container-images/jboss-eap-7-openshift-image pull request #464
Opened 2022-02-17 06:38 UTC by luck3y

https://issues.redhat.com/browse/CLOUD-4080
Signed-off-by: Ken WIlls <kwills@redhat.com>

Thanks for submitting your Pull Request!

Please make sure your PR meets the following requirements:

- [ ] Pull Request title is properly formatted: `[CLOUD-XYA] Subject`
- [ ] Pull Request contains link to the JIRA issue
- [ ] Pull Request contains description of the issue
- [ ] Pull Request does not include fixes for issues other than the main ticket
- [ ] Attached commits represent units of work and are properly formatted
- [ ] You have read and agreed to the Developer Certificate of Origin (DCO) (see `CONTRIBUTING.md`)
- [ ] Every commit contains `Signed-off-by: Your Name <yourname@example.com>` - use `git commit -s`

2022-02-17 08:16 UTC, jmesnil requested changes
Outside of my comment, this looks good to me.

That's great to have the JDK17 image built (even though it might not be published when EAP XP 4 is released).

2022-02-17 08:16 UTC, jmesnil commented on eap-xp4/runtime-image/test/Dockerfile
> +FROM jboss-eap-7/eap-xp3-openjdk11-runtime-openshift-rhel8
base image is still pointing to EAP XP 3

2022-02-17 08:48 UTC, jfdenise commented on eap-xp4/image.yaml
> +                  ref: 0.26.0
0.26.0 is for WF26. We are still on EAP 7.4.x, should be 0.23.4

2022-02-17 08:50 UTC, luck3y commented
Ok, cool -- thanks I wanted to make sure with you.

On Thu, Feb 17, 2022, 02:49 Jean-François Denise ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In eap-xp4/image.yaml
> <https://github.com/jboss-container-images/jboss-eap-7-openshift-image/pull/464#discussion_r808803240>
> :
>
> > +          - name: cct_module
> +            git:
> +                  url: https://github.com/jboss-openshift/cct_module.git
> +                  ref: 0.45.3
> +          - name: jboss-eap-modules
> +            git:
> +                  url: https://github.com/jboss-container-images/jboss-eap-modules.git
> +                  ref: EAP_XP4_RC1
> +          - name: jboss-eap-7-image
> +            git:
> +                  url: https://github.com/jboss-container-images/jboss-eap-7-image.git
> +                  ref: EAP_XP4_RC1
> +          - name: wildfly-cekit-modules
> +            git:
> +                  url: https://github.com/wildfly/wildfly-cekit-modules.git
> +                  ref: 0.26.0
>
> 0.26.0 is for WF26. We are still on EAP 7.4.x, should be 0.23.4
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/jboss-container-images/jboss-eap-7-openshift-image/pull/464#pullrequestreview-885613825>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAC7HAGWXZKY2SFAIELFVG3U3SY77ANCNFSM5OTXYUJQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> <jboss-container-images/jboss-eap-7-openshift-image/pull/464/review/885613825
> @github.com>
>

2022-02-17 13:59 UTC, luck3y commented
@jmesnil @jfdenise Thanks, updated.

2022-02-17 23:04 UTC, luck3y commented
This should be all set now.

2022-03-03 16:03 UTC, jmesnil submitted a review, later dismissed

2022-05-31 07:21 UTC, jmesnil approved these changes

2022-05-31 21:01 UTC, merged